#!/bin/bash

GIT_ANDIX_OPENWRT="https://github.com/anpaza/andix-openwrt.git"

function setup_colors() {
    # ANSI colors
    DRED="[0;31m"
    RED="[1;31m"
    DGREEN="[0;32m"
    GREEN="[1;32m"
    BROWN="[0;33m"
    YELLOW="[1;33m"
    WHITE="[1;37m"
    RESET="[0m"
}

function check_openwrt() {
	if [ ! -d openwrt ] ; then
		echo "${RED}OpenWrt repository not downloaded!${RESET}"
		return 1
	fi

	return 0;
}

function ow() {
		pushd openwrt &>/dev/null
		$*
		rc=$?
		popd &>/dev/null
		return $rc
}

function download_openwrt() {
	if [ -d openwrt ] ; then
		echo "${RED}Directory openwrt already exists!${RESET}"
		echo "${RED}Are you sure you want to remove the directory${RESET}"
		read -p "${RED}and download everything again? ${WHITE}" key
		echo ${RESET}
		case $key in
			y|Y)
				;;
			*)
				return
				;;
		esac
		echo "${GREEN}Removing directory 'openwrt' ...${RESET}"
		rm -rf openwrt
	fi

	echo "${GREEN}Cloning the 'andix-openwrt' repository ...${RESET}"
	git clone "$GIT_ANDIX_OPENWRT" openwrt
}

function configure_openwrt() {
	check_openwrt || return

	echo "${GREEN}Configuring OpenWrt for AndiX ...${RESET}"

	if [ ! -h openwrt/target/linux/andix ] ; then
		rm -rf openwrt/target/linux/andix
		ln -fs `readlink -f target-andix` openwrt/target/linux/andix
	fi
	if [ ! -f openwrt/.config ] ; then
		cp target-andix/openwrt-config-diff openwrt/.config
		ow make defconfig
	fi
	ow make menuconfig
}

function build_openwrt() {
	check_openwrt || return

	echo "${GREEN}Building OpenWrt, please sit back for a hour or so ...${RESET}"

	ow make
}

function main_menu() {
	cat <<EOF

${GREEN}Please choose what you want to do now:

    ${WHITE}1. ${BROWN}Download the OpenWrt repository.${RESET}
    ${WHITE}2. ${BROWN}Configure OpenWrt for AndiX.${RESET}
    ${WHITE}3. ${BROWN}Build AndiX.${RESET}
    ${WHITE}4. ${BROWN}Run AndiX in QEMU.${RESET}

    ${WHITE}0. ${BROWN}Quit now${RESET}

EOF

        key=0
	read -p "${DRED}Enter action number: ${WHITE}" key
	echo ${RESET}

	case $key in
		1)
			download_openwrt
			;;
		2)
			configure_openwrt
			;;
		3)
			build_openwrt
			;;
		4)
			./qemu-run-AndiX
			;;
		0)
			quit=yes
			;;
		*)
			echo ${RED}"wrong input"
			;;
	esac
}

setup_colors

cat <<EOF
${YELLOW}This simple script will help you set up for the first time.${RESET}
${YELLOW}If you're not sure, just execute all actions in sequence.${RESET}
EOF

quit=
while [ "$quit" == "" ] ; do
	main_menu
done
